### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by emctague** [Hnaguski/userChrome.css#1]
Hello, I'm interested in Forking this repo with some tweaks I've made, so I'm curious about licensing - how is this code licensed? Is it OK for me to fork it?

**Comment by kotajacob** [comment]
I just messaged him about adding a license (pretty sure he's going to just use gpl3)

(also technically since it's on github you're allowed to fork it by githubs terms of service, but adding a license is a good idea)

**Comment by Hnaguski** [comment]
I just lisenced it under MIT, so you're good to do whatever. I hadn't lisenced it yet because I didn't think anyone would see the repo just yet, sorry for the wait.
